name: check

on:  
  push:
    branches:
      - master
  pull_request:
    branches:
      - *

jobs:
  check-open-api:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2