name: check

on: [push]
      
jobs:
  check-open-api:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/checkout@v2
    - name: Validate OpenAPI definition
      uses: char0n/swagger-editor-validate@v1
      with:
        definition-file: future.yaml