name: check

on: push
      
jobs:
  check-open-api:
    name: open-api-check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Lint swagger file
      uses: crudo/spectral-action
      with:
        file_path: future.yaml

    - name: Lint swagger file 2
      uses: crudo/spectral-action
      with:
        file_path: future2.yaml
